---
- name: run runit-man
  command: runit-man -f '<%= node[:runit][:sv_dir] %>' -a '<%= node[:runit][:service_dir] %>' --rackup 'rainbows -p <%= node[:runit_man][:port] %>' -m <%= node[:runit_man][:mode] %> <% node[:runit_man][:files].each do |path| %> -v '<%= path %>'<% end %> <% node[:runit_man][:users].each do |user| %> -u '<%= user %>'<% end %> -l '<%= node[:runit_man][:logger] %>'
